See [README](https://github.com/samdeverett/metabolomics-llm/blob/glutamate/metabolomics-llm/glutamate/README.md) for experiment motivation.

# Experiment 1: `Synthesis`

**Question:** Can the LLM combine insights from the various pieces of context given to it? Does it provide a balanced response if the pieces of context disagree?
  
**Methodology:** Generate a natural language summary of the result from each paper. With the summaries prepended to the prompt, ask the LLM about the effect of exercise on glutamate and assess it's ability to synthesize the summaries.

In [2]:
question = "How does the presence of glutamate change in response to exercise?"

In [3]:
# Summary of results from each paper

breit = """
  Table 1 shows that exercise causes an increase in glutamate, specifically a 1.12 MFC and 0.17 log_2(MFC).
"""

peake = """
  The plasma concentration of glutamate increased significantly only during high-intensity interval exercise.
  In skeletal muscle, glutamate consumption increases markedly during the first few minutes of exercise, particularly when muscle glycogen is low.
"""

zauber = """
  Table 2 shows an increase in glutamate in both males and females during exercise, although only significantly for females.
"""

howe = """
  Table 1 shows a ratio of 0.528 for glutamate after an 80.5km run versus before, suggesting a decrease in glutamate in response to exercise.
"""

coelho = """
  Glutamate was up regulated immediately following exercise but returned to origin levels shortly after.
"""

danaher = """
  Glutamate significantly decreased during the recovery period after exercise.
"""

In [4]:
import pipeline

from apikey import HF_AUTH_TOKEN

In [5]:
# Select model to use
model_id = 'meta-llama/Llama-2-7b-chat-hf'

In [7]:
# # Load Model
model = pipeline.init_model(model_id, HF_AUTH_TOKEN)
tokenizer = pipeline.init_tokenizer(model_id, HF_AUTH_TOKEN)
text_generation_pipeline = pipeline.init_text_generation_pipeline(
    model,
    tokenizer,
    max_new_tokens=4096,
    do_sample=True,
    temperature=0.6,
    top_p=0.9,
    repetition_penalty=1.1
)
llm = pipeline.init_langchain_pipeline(text_generation_pipeline)

In [31]:
prompt = f"""
<s>[INST] <<SYS>>
Act as a helpful research assistant capable of synthesizing insights.
<</SYS>>
Using the following summaries of research papers, answer the question at the end.
If results from papers conflict with one another, say so; do not choose a side.
Remember to synthesize results rather than just restate them.
Summary of Breit paper: {breit}
Summary of Peake paper: {peake}
Summary of Zauber paper: {zauber}
Summary of Howe paper: {howe}
Summary of Coelho paper: {coelho}
Summary of Danaher paper: {danaher}
QUESTION: {question}
ANSWER: [/INST]
"""

Due to the stochastic nature of causal language models, let's ask this prompt several times to assess the quality of responses.

In [35]:
response = llm(prompt)
print(response)

Based on the summaries provided, it appears that there is some inconsistency in how glutamate levels change in response to exercise. Here are the main findings from each study:

* Breit et al. (2016) found that exercise caused an increase in glutamate levels by 1.12 million fold cells (MFC) and 0.17 log_2(MFC).
* Peake et al. (2017) found that glutamate levels in plasma increased significantly only during high-intensity interval exercise, and that glutamate consumption in skeletal muscle increases markedly during the first few minutes of exercise, particularly when muscle glycogen is low.
* Zauber et al. (2018) found that glutamate levels increased in both males and females during exercise, although only significantly for females.
* Howe et al. (2019) found that glutamate levels decreased after an 80.5km run, with a ratio of 0.528 compared to pre-exercise levels.
* Coelho et al. (2020) found that glutamate was upregulated immediately following exercise but returned to baseline levels s

In [33]:
response = llm(prompt)
print(response)

Based on the summarized research papers, it appears that the presence of glutamate changes in response to exercise in different ways depending on the type and intensity of exercise. Here are some key findings:

* Exercise can cause an increase in glutamate levels, as shown by the Breit et al. study (1.12 MFC and 0.17 log_2(MFC) increase in Table 1).
* However, this increase may not be observed in all types of exercise, as suggested by the Peake et al. study, which found that glutamate concentrations only increased significantly during high-intensity interval exercise.
* Additionally, the timing and duration of glutamate increase seem to vary, as the Peake et al. study found that glutamate consumption increases markedly during the first few minutes of exercise, particularly when muscle glycogen is low.
* The Zauber et al. study found that glutamate levels increased in both males and females during exercise, although the significance of the increase was only observed in females.
* Intere

In [32]:
response = llm(prompt)
print(response)

Based on the summarized research papers, it appears that there is a complex and dynamic relationship between glutamate and exercise. Here are some key findings:

1. Exercise can lead to an increase in glutamate levels:
	* Breit et al. (2019) found that exercise resulted in a significant increase in glutamate concentrations in the brain, specifically a 1.12 MFC and 0.17 log_2(MFC).
	* Peake et al. (2016) observed an increase in plasma glutamate concentrations during high-intensity interval exercise.
	* Zauber et al. (2018) reported a significant increase in glutamate levels in both males and females during exercise, although only for females.
2. Glutamate levels may fluctuate during exercise:
	* Howe et al. (2017) found that glutamate levels decreased after an 80.5km run, suggesting a decrease in glutamate in response to prolonged exercise.
	* Coelho et al. (2015) observed an immediate increase in glutamate levels following exercise, which returned to baseline levels soon after.
3. The 

#### Analysis

Each response correctly calls out the complexity of the relationship between exercise and glutamate. That's a major positive result.

That said, only the last response meaningfully synthesizes the results rather than restates the summaries. There is likely a need for more prompt engineering to ensure this happens more often.

### Larger Models

The responses above are from the 7B version of Llama 2. Let's see if the larger versions produce notably better responses given the same prompt, system prompt, and hyperparameters.

[Llama 2 13B](https://huggingface.co/spaces/huggingface-projects/llama-2-13b-chat):

> Based on the summaries of the research papers provided, there is evidence to suggest that exercise can cause changes in the levels of glutamate in the body. However, the specifics of these changes are not entirely clear and may depend on factors such as the intensity and duration of exercise, as well as individual differences among people.
>
> The Breit paper found an increase in glutamate levels (specifically, a 1.12 MFC and 0.17 log_2(MFC)) after exercise (Table 1). The Peake paper also found an increase in plasma glutamate concentrations during high-intensity interval exercise, particularly when muscle glycogen was low (Table 1). The Zauber paper found an increase in glutamate levels in both males and females during exercise, although the increase was only significant for females (Table 2).
>
> On the other hand, the Howe paper found a decrease in glutamate levels after an 80.5km run (ratio of 0.528 before vs. after), while the Coelho paper found that glutamate was upregulated immediately following exercise but returned to baseline levels shortly after. Finally, the Danaher paper found that glutamate significantly decreased during the recovery period after exercise.
>
> In summary, the results of these studies suggest that exercise can lead to changes in glutamate levels, but the direction and extent of these changes may vary depending on the specifics of the exercise and the individual. It is important to note that these findings are based on limited information and more research is needed to fully understand how exercise affects glutamate levels in the body.

[Llama 2 70B](https://huggingface.co/spaces/ysharma/Explore_llamav2_with_TGI):

> The presence of glutamate appears to change differently depending on the intensity, duration, and individual factors related to exercise. According to the summaries provided, here are some observations:
> 1. High-intensity interval exercise: The Peake paper indicates that plasma glutamate concentrations increase significantly during high-intensity interval exercise.
> 2. Muscle glycogen depletion: The Peake paper also suggests that glutamate consumption in skeletal muscle increases markedly during the first few minutes of exercise, particularly when muscle glycogen is low.
> 3. Gender differences: The Zauber paper shows an increase in glutamate during exercise for both males and females, but the increase is only significant for females.
> 4. Endurance exercise: The Howe paper suggests a decrease in glutamate after an 80.5km run.
> 5. Short-term exercise: The Coelho paper indicates that glutamate is upregulated immediately following exercise but returns to original levels shortly after.
> 6. Recovery period: The Danaher paper shows that glutamate significantly decreases during the recovery period after exercise.
>
> In summary, the presence of glutamate seems to be affected by various factors related to exercise, including intensity, duration, gender, and individual differences. While some studies suggest an increase in glutamate during or after exercise, others indicate a decrease. It is essential to consider the specific conditions of each study when interpreting the results. Further research may help clarify the overall effect of exercise on glutamate levels and provide a more comprehensive understanding of its role in exercise physiology.

These responses also acknowledge the conflict in results and arguably do a better job providing more helpful responses, suggesting that scaling to larger models may further increase quality.